In [5]:
import matplotlib as pyplot
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("/content/spotify_2014_2020_dataset.csv")

In [7]:
df.head()

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love

In [8]:

df.columns

Index(['Track_ID', 'Track_Name', 'Duration_Min', 'Artists', 'Release_Date',
       'Year', 'Query'],
      dtype='object')

In [9]:
df.tail()

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad
1700,7lidXGPXPYLNThITAOTlkK,You should be sad,3.42,Halsey,1/17/2020,2020,sad

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1701 entries, 0 to 1700
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Track_ID      1701 non-null   object
 1   Track_Name    1701 non-null   object
 2   Duration_Min  1701 non-null   float64
 3   Artists       1701 non-null   object
 4   Release_Date  1701 non-null   object
 5   Year          1701 non-null   int64
 6   Query         1701 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 93.2+ KB

In [11]:
df.describe()

       Duration_Min         Year
count   1701.000000  1701.000000
mean       4.268595  2016.513815
std        5.260055     1.854553
min        3.000000  2014.000000
25%        3.460000  2015.000000
50%        3.830000  2016.000000
75%        4.320000  2018.000000
max      180.470000  2020.000000

In [12]:
df.shape

(1701, 7)

In [13]:
useless=df[["Track_ID","Duration_Min"]]

In [14]:
df.loc[0]

Track_ID        6dBUzqjtbnIa1TwYbyw5CM
Track_Name                 Lovers Rock
Duration_Min                      3.57
Artists                        TV Girl
Release_Date                  6/5/2014
Year                              2014
Query                             love
Name: 0, dtype: object

In [15]:
df.iloc[0,1]

'Lovers Rock'

In [16]:
df.iloc[0:7]

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love
5,48td6xvpokdYwvbl3JIiXP,Love Never Felt So Good,4.11,"Michael Jackson, Justin Timberlake",5/9/2014,2014,love
6,3sslYZcFKtUvIEWN9lADgr,First Love/Late Spring,4.64,Mitski,11/11/2014,2014,love

In [17]:
df.loc[0:6,["Track_ID","Duration_Min"]]

                 Track_ID  Duration_Min
0  6dBUzqjtbnIa1TwYbyw5CM          3.57
1  5J4ZkQpzMUFojo1CtAZYpn          3.94
2  2e3Ea0o24lReQFR4FA7yXH          3.52
3  6nGeLlakfzlBcFdZXteDq7          5.27
4  5BJSZocnCeSNeYMj3iVqM7          3.74
5  48td6xvpokdYwvbl3JIiXP          4.11
6  3sslYZcFKtUvIEWN9lADgr          4.64

In [18]:
df.iat[2,3]

'J. Cole'

In [19]:
df.at[0,"Duration_Min"]

np.float64(3.57)

In [20]:
df.head()

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love

In [23]:
df[df["Duration_Min"]==3.00]

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
896,6pnD89Q888HUHhcwQUTky8,Free Animal,3.0,Foreign Air,9/23/2016,2016,rock
1064,2wxfu24GQpEZQrjDJm5Ac1,Every Little Thing,3.0,Carly Pearce,10/13/2017,2017,sad
1281,0V4aRCAMBblWlRGTjiyMRR,Fetish Remix (feat. Young Thug),3.0,"Lil Keed, Young Thug",9/14/2018,2018,remix

In [36]:
df.query("Duration_Min==3.00 and Year>2014")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
896,6pnD89Q888HUHhcwQUTky8,Free Animal,3.0,Foreign Air,9/23/2016,2016,rock
1064,2wxfu24GQpEZQrjDJm5Ac1,Every Little Thing,3.0,Carly Pearce,10/13/2017,2017,sad
1281,0V4aRCAMBblWlRGTjiyMRR,Fetish Remix (feat. Young Thug),3.0,"Lil Keed, Young Thug",9/14/2018,2018,remix

In [39]:
col="Year"
df.query(f"{col}>2014")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
299,3zHq9ouUJQFQRf3cm1rRLu,"Love Me Like You Do - From ""Fifty Shades Of Grey""",4.21,Ellie Goulding,11/6/2015,2015,love
300,50kpGaPAhYJ3sGmk6vplg0,Love Yourself,3.90,Justin Bieber,11/13/2015,2015,love
301,7B5Npv8NjjTCzk8PLpU66h,Love In The Dark,4.77,Adele,11/20/2015,2015,love
302,1D0QeY6vwnZcbiM6iBYYSj,Love Like Ghosts,3.73,Lord Huron,4/7/2015,2015,love
303,5h9hkYIBWTZYFRmF6Iz1gt,Love/Paranoia,3.10,Tame Impala,7/17/2015,2015,love
...,...,...,...,...,...,...,...
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad
1700,7lidXGPXPYLNThITAOTlkK,You should be sad,3.42,Halsey,1/17/2020,2020,sad

In [47]:
df.query("Year>2015 and Query=='sad'")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
765,1Be8liECvEP5NYZjYvukbI,She Ain't In It,3.31,Jon Pardi,5/13/2016,2016,sad
766,75ZvA4QfFiZvzhj2xkaWAh,I Fall Apart,3.72,Post Malone,12/9/2016,2016,sad
767,35r28RDot7nPE7y9K9H7l0,Feeling Whitney,4.29,Post Malone,12/9/2016,2016,sad
768,1N7qGCKRRnvjoy8MGyHgpS,Came Here to Forget,3.67,Blake Shelton,5/20/2016,2016,sad
769,04boE4u1AupbrGlI62WvoO,White Noise 3 Hour Long,180.47,White Noise Therapy,12/4/2016,2016,sad
...,...,...,...,...,...,...,...
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad
1700,7lidXGPXPYLNThITAOTlkK,You should be sad,3.42,Halsey,1/17/2020,2020,sad