In [123]:
import matplotlib as pyplot
import pandas as pd
import numpy as np

In [124]:
df=pd.read_csv("/content/spotify_2014_2020_dataset.csv")

In [125]:
df.head()

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love

In [126]:

df.columns

Index(['Track_ID', 'Track_Name', 'Duration_Min', 'Artists', 'Release_Date',
       'Year', 'Query'],
      dtype='object')

In [127]:
df.tail()

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad
1700,7lidXGPXPYLNThITAOTlkK,You should be sad,3.42,Halsey,1/17/2020,2020,sad

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1701 entries, 0 to 1700
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Track_ID      1701 non-null   object
 1   Track_Name    1701 non-null   object
 2   Duration_Min  1701 non-null   float64
 3   Artists       1701 non-null   object
 4   Release_Date  1701 non-null   object
 5   Year          1701 non-null   int64
 6   Query         1701 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 93.2+ KB

In [129]:
df.describe()

       Duration_Min         Year
count   1701.000000  1701.000000
mean       4.268595  2016.513815
std        5.260055     1.854553
min        3.000000  2014.000000
25%        3.460000  2015.000000
50%        3.830000  2016.000000
75%        4.320000  2018.000000
max      180.470000  2020.000000

In [130]:
df.shape

(1701, 7)

In [131]:
useless=df[["Track_ID","Duration_Min"]]

In [132]:
df.loc[0]

Track_ID        6dBUzqjtbnIa1TwYbyw5CM
Track_Name                 Lovers Rock
Duration_Min                      3.57
Artists                        TV Girl
Release_Date                  6/5/2014
Year                              2014
Query                             love
Name: 0, dtype: object

In [133]:
df.iloc[0,1]

'Lovers Rock'

In [134]:
df.iloc[0:7]

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love
5,48td6xvpokdYwvbl3JIiXP,Love Never Felt So Good,4.11,"Michael Jackson, Justin Timberlake",5/9/2014,2014,love
6,3sslYZcFKtUvIEWN9lADgr,First Love/Late Spring,4.64,Mitski,11/11/2014,2014,love

In [135]:
df.loc[0:6,["Track_ID","Duration_Min"]]

                 Track_ID  Duration_Min
0  6dBUzqjtbnIa1TwYbyw5CM          3.57
1  5J4ZkQpzMUFojo1CtAZYpn          3.94
2  2e3Ea0o24lReQFR4FA7yXH          3.52
3  6nGeLlakfzlBcFdZXteDq7          5.27
4  5BJSZocnCeSNeYMj3iVqM7          3.74
5  48td6xvpokdYwvbl3JIiXP          4.11
6  3sslYZcFKtUvIEWN9lADgr          4.64

In [136]:
df.iat[2,3]

'J. Cole'

In [137]:
df.at[0,"Duration_Min"]

np.float64(3.57)

In [138]:
df.head()

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love

In [139]:
df[df["Duration_Min"]==3.00]

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
896,6pnD89Q888HUHhcwQUTky8,Free Animal,3.0,Foreign Air,9/23/2016,2016,rock
1064,2wxfu24GQpEZQrjDJm5Ac1,Every Little Thing,3.0,Carly Pearce,10/13/2017,2017,sad
1281,0V4aRCAMBblWlRGTjiyMRR,Fetish Remix (feat. Young Thug),3.0,"Lil Keed, Young Thug",9/14/2018,2018,remix

In [140]:
df.query("Duration_Min==3.00 and Year>2014")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
896,6pnD89Q888HUHhcwQUTky8,Free Animal,3.0,Foreign Air,9/23/2016,2016,rock
1064,2wxfu24GQpEZQrjDJm5Ac1,Every Little Thing,3.0,Carly Pearce,10/13/2017,2017,sad
1281,0V4aRCAMBblWlRGTjiyMRR,Fetish Remix (feat. Young Thug),3.0,"Lil Keed, Young Thug",9/14/2018,2018,remix

In [141]:
col="Year"
df.query(f"{col}>2014")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
299,3zHq9ouUJQFQRf3cm1rRLu,"Love Me Like You Do - From ""Fifty Shades Of Grey""",4.21,Ellie Goulding,11/6/2015,2015,love
300,50kpGaPAhYJ3sGmk6vplg0,Love Yourself,3.90,Justin Bieber,11/13/2015,2015,love
301,7B5Npv8NjjTCzk8PLpU66h,Love In The Dark,4.77,Adele,11/20/2015,2015,love
302,1D0QeY6vwnZcbiM6iBYYSj,Love Like Ghosts,3.73,Lord Huron,4/7/2015,2015,love
303,5h9hkYIBWTZYFRmF6Iz1gt,Love/Paranoia,3.10,Tame Impala,7/17/2015,2015,love
...,...,...,...,...,...,...,...
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad
1700,7lidXGPXPYLNThITAOTlkK,You should be sad,3.42,Halsey,1/17/2020,2020,sad

In [142]:
df_unique=df.drop_duplicates("Query")

In [143]:
df_unique

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
46,5O2P9iiztwhomNh8xkR9lJ,Night Changes,3.78,One Direction,11/17/2014,2014,night
93,7t2bFihaDvhIrd2gn2CWJO,"Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mus...",4.05,"Ty Dolla $ign, The Weeknd, Wiz Khalifa, Mustard",6/10/2014,2014,remix
151,11MyiSGZSYSmhhqwGUTtAq,Sad Girl,5.30,Lana Del Rey,1/1/2014,2014,sad
231,1O9D7P7Z1wMJXW19zTXrXi,Go Away,3.23,"Weezer, Best Coast",10/1/2014,2014,rock

In [144]:
df.query("Query=='rock'")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
231,1O9D7P7Z1wMJXW19zTXrXi,Go Away,3.23,"Weezer, Best Coast",10/1/2014,2014,rock
232,2vyae4DvSU2gs8OMOGwXF2,Rock or Bust,3.05,AC/DC,11/28/2014,2014,rock
233,0755vnFQZLSgHHWbR1qCjY,Rocket,6.53,Beyoncé,11/24/2014,2014,rock
234,5hheGdf1cb4rK0FNiedCfK,The Devil in I,5.71,Slipknot,10/15/2014,2014,rock
235,5fVl28RgREvxVtGSf9OsbK,Meddle About,3.40,Chase Atlantic,12/25/2014,2014,rock
...,...,...,...,...,...,...,...
1580,3fnPv1LRMxENr63afVhaz1,Honky Tonk Women,3.05,The Rolling Stones,11/29/2019,2019,rock
1581,4GZ3YCkuH0VvTluVLwUp4g,I Just Wanna Shine,3.47,Fitz and The Tantrums,9/20/2019,2019,rock
1582,1z5YtEopKg5pyjCM3BEsr5,Dead Man Walking,3.12,Jeremy Camp,9/20/2019,2019,rock
1583,5utAceRFzBzXUkHrkwSklB,LIKE A ROCKSTAR,3.47,Chase Atlantic,1/25/2019,2019,rock
1584,5icbZiF6lcuEORG0UzMsS2,Every Time You Leave,3.61,"I Prevail, Delaney Jane",3/29/2019,2019,rock

In [145]:
df.query("Query=='love'")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love
...,...,...,...,...,...,...,...
1611,5cZx05fE3nAdFqXlXPUacZ,Lovesong,9.29,Common Saints,10/9/2020,2020,love
1612,64LP4oTxEweNfKTCTGLhtg,Love Is a Dead End Road,3.26,Tyler Braden,8/7/2020,2020,love
1613,140dx97IbJbQhIMd7AaHeb,love nwantiti (ah ah ah) [feat. Joeboy & Kuami...,3.13,"CKay, Joeboy, Kuami Eugene",2/13/2020,2020,love
1614,3JP7KdSVvcX3mTfitBp2Ec,Love Cycle (with Summer Walker),3.59,"Toosii, Summer Walker",9/18/2020,2020,love
1615,4l0Mvzj72xxOpRrp6h8nHi,Lose You To Love Me,3.44,Selena Gomez,1/10/2020,2020,love

In [146]:
df.query("Query=='remix'")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
93,7t2bFihaDvhIrd2gn2CWJO,"Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mus...",4.05,"Ty Dolla $ign, The Weeknd, Wiz Khalifa, Mustard",6/10/2014,2014,remix
94,0zVMzJ37VQNFUNvdxxat2E,Flawless Remix (feat. Nicki Minaj),3.91,"Beyoncé, Nicki Minaj",11/24/2014,2014,remix
95,0QBDmhUqCEFtxA6OoAktKC,Lonely (feat. Young Scooter) - Remix,3.11,"Speaker Knockerz, Young Scooter",9/2/2014,2014,remix
96,3zSCNTXI7Ed0PiidZVmzIe,Ignition - Remix,3.10,R. Kelly,5/19/2014,2014,remix
97,62N2JSA0jHmSH7Va9t7hIf,Habits (Stay High) - Hippie Sabotage Remix,4.32,"Tove Lo, Hippie Sabotage",1/1/2014,2014,remix
...,...,...,...,...,...,...,...
1682,2uu2aGqA2UblCg581Q7l1g,Caramelo - Remix,3.89,"Ozuna, KAROL G, Myke Towers",8/17/2020,2020,remix
1683,7LE1K0lZyRFZjSlrnm7lfD,"La Curiosidad (feat. Dj Nelson, JHAYCO, Lunay ...",6.38,"Jay Wheeler, Myke Towers, Rauw Alejandro, DJ N...",12/17/2020,2020,remix
1684,5ofPzkJ57L6IWXPmnb4f0C,Seeing & Believing - Kolter Remix,3.53,"Chris Stussy, Kolter",10/12/2020,2020,remix
1685,6KgYfOQXAJYaKP3ZyRrxyK,Everybody - Remix,3.28,"Boosie Badazz, MO3",2/14/2020,2020,remix
1686,7kRVWQ1G4o8w3ubfNW2ZHB,Wavy (Remix) [feat. Travis Scott],4.01,"Lil Keed, Travis Scott",8/7/2020,2020,remix

In [147]:
df.query("Query=='sad'")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
151,11MyiSGZSYSmhhqwGUTtAq,Sad Girl,5.30,Lana Del Rey,1/1/2014,2014,sad
152,1JY6B9ILvmRla2IKKRZvnH,Sad Machine,5.84,Porter Robinson,8/8/2014,2014,sad
153,1CS7Sd1u5tWkstBhpssyjP,Take Me to Church,4.03,Hozier,9/19/2014,2014,sad
154,0ZfByLXCeKchuj7zi1CJ0S,Stolen Dance,5.23,Milky Chance,10/14/2014,2014,sad
155,6cK2sGKIwGoYdh9mMZFqRb,Sadnecessary,4.97,Milky Chance,10/14/2014,2014,sad
...,...,...,...,...,...,...,...
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad
1700,7lidXGPXPYLNThITAOTlkK,You should be sad,3.42,Halsey,1/17/2020,2020,sad

In [148]:
df.query("Query=='night'")

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
46,5O2P9iiztwhomNh8xkR9lJ,Night Changes,3.78,One Direction,11/17/2014,2014,night
47,3idU3rXoFCEFhAAbPGbwht,The Night Is Still Young,3.79,Nicki Minaj,12/12/2014,2014,night
48,4bBrKDo8rchikwZOtmXbIH,The Night Is Still Young,3.79,Nicki Minaj,12/15/2014,2014,night
49,1xBRGN41DWx2vwNFY5CvGe,Night Witches,3.02,Sabaton,5/16/2014,2014,night
50,6Xa2q0dapj03CsRzmD0Os5,Fight Night,3.60,Migos,2/25/2014,2014,night
...,...,...,...,...,...,...,...
1642,58HvfVOeJY7lUuCqF0m3ly,MIDDLE OF THE NIGHT,3.07,Elley Duhé,1/10/2020,2020,night
1643,1Ynv5ahQNdRRgDGcMVa3Y6,Friday Night,4.10,King George,11/12/2020,2020,night
1644,2o7kljiAHz8ypMLVmzmFqg,Nightcall,4.10,"Essenger, NINA",11/25/2020,2020,night
1645,5PeMQiULHTknXhyisgOyXu,Nightmare,3.98,"GAWNE, Dansonn, SkyDxddy",1/24/2020,2020,night
1646,4pqfAjOdONW9IGHq5BV328,Nights Alone,3.35,Broadside,7/24/2020,2020,night

In [149]:
year1_release=df.query("2014 < Year <2016")

In [150]:
year1_release

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
299,3zHq9ouUJQFQRf3cm1rRLu,"Love Me Like You Do - From ""Fifty Shades Of Grey""",4.21,Ellie Goulding,11/6/2015,2015,love
300,50kpGaPAhYJ3sGmk6vplg0,Love Yourself,3.90,Justin Bieber,11/13/2015,2015,love
301,7B5Npv8NjjTCzk8PLpU66h,Love In The Dark,4.77,Adele,11/20/2015,2015,love
302,1D0QeY6vwnZcbiM6iBYYSj,Love Like Ghosts,3.73,Lord Huron,4/7/2015,2015,love
303,5h9hkYIBWTZYFRmF6Iz1gt,Love/Paranoia,3.10,Tame Impala,7/17/2015,2015,love
...,...,...,...,...,...,...,...
590,4Fx8dpPrAtwSlg1XEwxMUF,Dern Kala,3.66,Khruangbin,11/6/2015,2015,rock
591,07BuyVse8pYAWd9DXD7B2D,Day Of The Dead,3.92,Hollywood Undead,3/31/2015,2015,rock
592,6hvSILCCQT5a0MRcOE36zd,Footsteps,4.37,Pop Evil,8/21/2015,2015,rock
593,1SmoikQyzvAi35I5X4LHMY,Gravity,4.07,Papa Roach,11/27/2015,2015,rock
594,3vtFowc9zcQfvqsLAZ9Cx2,Shadows,3.48,Pastel Ghost,3/10/2015,2015,rock

In [151]:
df.isnull().sum()

Track_ID        0
Track_Name      0
Duration_Min    0
Artists         0
Release_Date    0
Year            0
Query           0
dtype: int64

In [152]:
new_df=df.dropna

In [153]:
new_df=df.dropna(axis=1)

In [154]:
new_df.shape

(1701, 7)

In [155]:
new_df.drop_duplicates()

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love
...,...,...,...,...,...,...,...
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad
1700,7lidXGPXPYLNThITAOTlkK,You should be sad,3.42,Halsey,1/17/2020,2020,sad

In [156]:
new_df.duplicated("Query")

0       False
1        True
2        True
3        True
4        True
        ...
1696     True
1697     True
1698     True
1699     True
1700     True
Length: 1701, dtype: bool

In [157]:
new_df=df.drop(["Track_ID","Release_Date"], axis=1)

In [158]:
new_df.query("Artists=='Ariana Grande'")

          Track_Name  Duration_Min        Artists  Year  Query
1215  goodnight n go          3.16  Ariana Grande  2018  night
1317         ghostin          4.52  Ariana Grande  2018    sad
1508         ghostin          4.52  Ariana Grande  2019    sad

In [159]:
df_artists= df.drop_duplicates(["Artists"])

In [160]:
df_artists

,Track_ID,Track_Name,Duration_Min,Artists,Release_Date,Year,Query
0,6dBUzqjtbnIa1TwYbyw5CM,Lovers Rock,3.57,TV Girl,6/5/2014,2014,love
1,5J4ZkQpzMUFojo1CtAZYpn,Love Me Harder,3.94,"Ariana Grande, The Weeknd",8/22/2014,2014,love
2,2e3Ea0o24lReQFR4FA7yXH,Love Yourz,3.52,J. Cole,12/9/2014,2014,love
3,6nGeLlakfzlBcFdZXteDq7,Love Story,5.27,Indila,1/1/2014,2014,love
4,5BJSZocnCeSNeYMj3iVqM7,Love Runs Out,3.74,OneRepublic,1/1/2014,2014,love
...,...,...,...,...,...,...,...
1695,0Al3wN3keprGTSgG8NBwjr,I Hope You’re Happy Now,3.31,"Carly Pearce, Lee Brice",2/14/2020,2020,sad
1696,2fyDWKsx5904KnZMGllmAv,A Sad Cartoon,5.26,Loathe,2/7/2020,2020,sad
1697,1y2GDXFvtHPbCkHFYg49Gn,Sudden Desire,3.13,Hayley Williams,5/8/2020,2020,sad
1698,5UBonaClAZVfzxJNn8nnhh,Brown Sleep Noise,4.13,Sleep Miracle,12/16/2020,2020,sad
1699,2pgDBO0ZAgvye7joSmdDm8,SAD GIRLZ LUV MONEY,3.27,"Amaarae, MOLIY",11/12/2020,2020,sad

In [161]:
df_artists.shape

(1240, 7)

In [162]:
new_df.dtypes

Track_Name       object
Duration_Min    float64
Artists          object
Year              int64
Query            object
dtype: object

In [169]:
new_df=new_df.sort_values("Duration_Min",)

In [167]:
new_df

,Track_Name,Duration_Min,Artists,Year,Query
896,Free Animal,3.00,Foreign Air,2016,rock
1281,Fetish Remix (feat. Young Thug),3.00,"Lil Keed, Young Thug",2018,remix
1064,Every Little Thing,3.00,Carly Pearce,2017,sad
1177,Love Hurts (feat. Travis Scott),3.01,"Playboi Carti, Travis Scott",2018,love
1108,Highway Tune,3.01,Greta Van Fleet,2017,rock
...,...,...,...,...,...
518,"Sleep and Relaxation Nature Sounds, Crickets S...",20.00,Acerting Art,2015,sad
384,A Night in the Forest,20.00,Acerting Art,2015,night
364,Night Time Forest Sounds,20.00,Acerting Art,2015,night
779,White Noise 2 Hour Long,120.01,White Noise Therapy,2016,sad
769,White Noise 3 Hour Long,180.47,White Noise Therapy,2016,sad